### ISSUE TITLE
Parsing Cache

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-library#102]
It was asked that the parsing objects cache the results across steps. So basically, it would query if it had parsed a given object before and return the results if it had. We'll need to invalidate the hash if the environment has changed.

**Comment by matthewfcarlson** [comment]
One suggestion would be to add the cache inside the parsers themselves.
Another would be a common object that plugins can access.

**Comment by spbrogan** [comment]
closed due to lack of interest and immediate need.
