### ISSUE TITLE
Stuart_setup on Ubuntu box 

### ISSUE THREAD

**Issue by sumanthvi** [tianocore/edk2-pytool-library#115]
Hi,

I tried  the setup as listed here:
https://github.com/tianocore/edk2/blob/master/EmulatorPkg/PlatformCI/ReadMe.md
on Ubuntu 18.04 LTS. 

Sumanth@sumanth-VirtualBox:~/edk2$ stuart_setup -c EmulatorPkg/PlatformCI/PlatformBuild.py TOOL_CHAIN_TAG=GCC5 
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
PROGRESS - ## Syncing Git repositories: CryptoPkg/Library/OpensslLib/openssl ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3 UnitTestFrameworkPkg/Library/CmockaLib/cmocka MdeModulePkg/Universal/RegularExpressionDxe/oniguruma MdeModulePkg/Library/BrotliCustomDecompressLib/brotli BaseTools/Source/C/BrotliCompress/brotli...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: CryptoPkg/Library/OpensslLib/openssl...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: UnitTestFrameworkPkg/Library/CmockaLib/cmocka...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: MdeModulePkg/Universal/RegularExpressionDxe/oniguruma...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: MdeModulePkg/Library/BrotliCustomDecompressLib/brotli...
PROGRESS - Done.

PROGRESS - ## Checking Git repository: BaseTools/Source/C/BrotliCompress/brotli...
PROGRESS - Done.

SECTION - Summary
PROGRESS - Success

stuart_update -c EmulatorPkg/PlatformCI/PlatformBuild.py TOOL_CHAIN_TAG=GCC5** 
SECTION - Init SDE
SECTION - Loading Plugins
SECTION - Start Invocable Tool
SECTION - Initial update of environment
UpdatingWARNING - [SDE] Failed to fetch NugetDependecy: mu_nasm@2.14.02: [Nuget] We failed to install this version 2.14.02 of mu_nasm
. Done
SECTION - Second pass update of environment
UpdatingWARNING - [SDE] Failed to fetch NugetDependecy: mu_nasm@2.14.02: [Nuget] We failed to install this version 2.14.02 of mu_nasm
. Done
ERROR - We were unable to successfully update 1 dependencies in environment
SECTION - Summary
ERROR - Error

How do i solve this issue on Ubuntu 18.04 LTS.

Regards,
Sumanth

**Comment by spbrogan** [comment]
Please take a look here: https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/usability/using_linux.md#setting-up-nugetmono

and here: https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/usability/using_extdep.md#a-note-on-nuget-on-linux

this should get you unblocked.

**Comment by matthewfcarlson** [comment]
I'm closing this issue, feel free to reopen it if you're still running into issues
