### ISSUE TITLE
Create move file and delete file utility functions

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-library#124]
Currently, there are many implementations of moving and deleting files (multiple retries, shutil, etc). A standardized error-tolerant approach would be beneficial to many.

**Comment by spbrogan** [comment]
Will implement a delete files.  Move is only in place and has more flexibility that we don't want to duplicate.

**Comment by spbrogan** [comment]
This will create new public API so assigning to 0.11.0 as it will not break compat going forward.
