### ISSUE TITLE
Benign bug

### ISSUE THREAD

**Issue by bkarstens** [tianocore/edk2-pytool-library#150]
For regex groups, enclosed by parentheses, `|` is needed to separate *expression 1* or *expression 2* (ex. `(a|b)`). For bracketed expressions, this is not needed (ex. `[ab]` or `[^ab]`). These patterns therefore include `|` as a possible path separator. Seeing as this character will not show up in paths, this is benign.
https://github.com/tianocore/edk2-pytool-library/blob/3de82123f055e65c3babbc4e5833121f4215af51/edk2toollib/gitignore_parser.py#L180-L181

**Comment by Javagedes** [comment]
@bkarstens I've updated the regex strings as you mentioned along with another change in #174. Feel free to review.
