### ISSUE TITLE
INFs in NuGet external dependencies not found in build report

### ISSUE THREAD

**Issue by makubacki** [tianocore/edk2-pytool-library#152]
If a project references INF files in a path to a NuGet ext_dep, the build report fails to find the INF file.

A project that does this can be built with the following command to reproduce the issue:

`stuart_build -c .\PlatformBuild.py TOOL_CHAIN_TAG=VS2019 BUILDREPORTING=TRUE BUILDREPORT_TYPES=FLASH`

This will result in an error such as the following:

```
...
ERROR - Failed to find Module by InfPath TestPkg/Binaries/NugetPackage.DEBUG_extdep/Source/Dir1/Dxe/DxeModule.inf
...
```

**Comment by Javagedes** [comment]
This is due to a combination adding the ext_dep to the package path list, and placing the ext_dep in the incorrect location. Build does not support nested packages paths (i.e. ```PackagePathList = ["a/b", "a/b/c"]. For this particular issue, the reason is that GetEdk2RelativePathFromAbsolutePath() uses PackagePathList for the conversion. The RelativePath will be different depending on if it uses "a/b" or "a/b/c". 

This brings up the need of verifying at build that there are no nested package paths in PackagePathList.
