### ISSUE TITLE
[Bug]: Raising exception for nested packages breaks some downstream builds.  Change to WARNING

### ISSUE THREAD

**Issue by mdkinney** [tianocore/edk2-pytool-library#192]
### Contact Details

michael.d.kinney@intel.com

### Describe the Bug

The following commit made on April 20, 2022 added a check for nested packages (nested .dec files) and raises an exception if a nested package is detected:

https://github.com/tianocore/edk2-pytool-library/commit/420e44a250c1b609398b839b30a2230e29016067

The specific line in path_utilities.py that raises this exception is as follows:

https://github.com/tianocore/edk2-pytool-library/blob/c9aac3b6496f93c5465bbcd9894876d7d6327d97/edk2toollib/uefi/edk2/path_utilities.py#L78

A commit to the edk2 repo on Nov 1, 2022 updated pip-requirements.txt the included this change from 6 months ago.

https://github.com/tianocore/edk2/commit/b5dbf8267b2596f4a28cdb30d1f533b958ddd4ed

When this commit was added to the edk2, any downstream consumers of the edk2 repo that use pytool stuart commands and have 1 or more nested packages immediately break their build with an exception stack trace.

No information was given for this new breaking behavior.

It is clear that nested packages are not allowed by the EDK II Specifications.  However, I recommend that this issue be noted as a WARNING in the stuart logs at this time, and raise to an ERROR after all downstream consumers have had a chance to evaluate and fix the WARNING condition.

The recommended change for this issue is to change

                    raise Exception(f'Nested packages not allowed. Pkg path [{package_path}] nested in Package [{p}]')

TO:

                    self.logger.log(logging.WARNING,f'Nested packages not allowed. Pkg path [{package_path}] nested in Package [{p}]')

### Reproduction steps

1. sync with edk2 repo after 11/2/2022.
2. use stuart_ci_build on a repo with one or more nested packages
3. stuart_ci_build raises exception for nested packages

### Expected behavior

stuart_ci_build should add a WARNING to the stuart logs when a nested package is detected

### Execution Environment

Windows
Python 3.8.8

### Pip packages

Package                Version
---------------------- ---------
antlr4-python3-runtime 4.7.1
edk2-basetools         0.1.39
edk2-pytool-extensions 0.19.1
edk2-pytool-library    0.11.6
future                 0.18.2
pefile                 2022.5.30
pip                    20.2.3
PyYAML                 6.0
semantic-version       2.10.0
setuptools             49.2.1

**Comment by Javagedes** [comment]
Resolved by #199 so that downstream platforms can resolve nested packages. This is a change that is immediately deprecated and will be removed in a future release. The removal of this deprecated feature will be tracked via #200.
