### ISSUE TITLE
[Feature]: Clarify the supported versions of python and add tests for each

### ISSUE THREAD

**Issue by spbrogan** [tianocore/edk2-pytool-library#201]
### What does the feature solve?

In this project it is not clear what versions of python are required, supported, and tested against.  This makes it harder for consumers of this project to know their requirements are.  It also makes it harder for the developers of this project as they don't know what language features they are allowed to use.  

### Describe the solution

1. Add documentation for the supported versions of python and the rationale and process.  
2. Update documentation, Pypi metadata to be accurate.
3. Add PR gate tests for the supported versions of python
4. Add CI gates and status badges for each supported version

### Additional context

As pytools  usage expands it is critical to communicate these things as well as provide roadmap to indicate how these change as python releases new versions.

**Comment by Javagedes** [comment]
@makubacki @spbrogan I vote to only garuntee support for last three major versions (so 3.9,3.10, 3.11). When 3.12 comes out we bump it to 3.10, 3.11, 3.12. I can setup a matrix for pipelines that changes the version and runs all tests.

**Comment by makubacki** [comment]
> @makubacki @spbrogan I vote to only garuntee support for last three major versions (so 3.9,3.10, 3.11). When 3.12 comes out we bump it to 3.10, 3.11, 3.12. I can setup a matrix for pipelines that changes the version and runs all tests.

I agree with n-3. This seems to capture the minimum version I've seen required in some environments right now (3.9). We've also discussed n-2 but I think n-3 is a good starting point.

**Comment by Javagedes** [comment]
Adding required python version for pypi in #223, but this does not solve the entire Issue.

**Comment by Javagedes** [comment]
Pushing this milestone back. This will be marked complete when I upgrade from pipelines to github actions similar to what was done in edk2-pytool-extensions. Holding off on this until we have something similar to mu_devops.
