### ISSUE TITLE
[Bug]: fails to install when offline

### ISSUE THREAD

**Issue by kraxel** [tianocore/edk2-pytool-library#235]
### Contact Details

just add a comment, and let github send out notifications 😎

### Describe the Bug

Installing the package without internet connection (standard procedure for linux distro packaging) fails because the installer wants download vswhere.exe.

Silently downloading stuff is bad practice.

In this specific case it also looks rather pointless to do this on linux machines, they typically wouldn't be able to run the binary anyway.

### Reproduction steps

1. clone git repo
2. disable network
3. try install package

### Expected behavior

install works

### What Python version are you using?

Python 3.11

### Execution Environment

Fedora 37

**Comment by Javagedes** [comment]
@kraxel Thank you for reporting this, I will look into the best way to resolve this

**Comment by Javagedes** [comment]
#240 will fix the issue with attempting to install vswhere on a linux system.
