### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LethargicHitman** [tianocore/edk2-pytool-library#297]
### Contact Details

sanjeevinishanth@gmail.com

### Describe the Bug

QueryVcVariables in edk2toollib\windows\locate_tools.py does not clearly mention the missing VC variables.
But it prints all the queried VC variables instead of just printing the missing keys.

The issue is in line number: 224.
`result_set = set(list(result.keys()))`

This should be changed to something like:
`result_set = set([key.upper() for key in (result.keys())])`

### Reproduction steps

The issue happens only on one of my devices. But the Visual studio setup seems to be fine.
However, to easily repro the issue, try building with an incomplete installation of Visual studio.

### Expected behavior

The expected behavior is that the error prints only the missing VC elements.

### What Python version are you using?

Python 3.9, Python 3.10, Python 3.11

### Execution Environment

Windows 10, Windows 11.
Python 3.10.7

### Pip packages

edk2-pytool-library    0.14.0

**Comment by Javagedes** [comment]
@LethargicHitman Thank you for submitting this bug. Apologies for not responding earlier, I missed that a bug was opened. I will take a look and try to reproduce.

**Comment by Javagedes** [comment]
@LethargicHitman this has been resolved and will be available in v0.15.0 of edk2-pytool-library.
