### ISSUE TITLE
[Feature]: stuart_report and NULL libraries for component-libs

### ISSUE THREAD

**Issue by apop5** [tianocore/edk2-pytool-library#500]
### What does the feature solve?

In a platform's DSC file, if a null library is specified in the [LibraryClasses] section, then the NULL instance will be linked against every driver.

https://github.com/microsoft/mu_basecore/blob/release/202302/MdePkg/MdeLibs.dsc.inc#L23

stuart_report component-libs does not include the NULL instances of libraries that are linked into the drivers, nor does it include the dependencies that are pulled in because of the NULL libraries.

### Describe the solution

NULL library classes instances should be automatically added to every module type of the stuart_parse.

**Comment by Javagedes** [comment]
closed by #499
