### ISSUE TITLE
Parser isn't working correctly for MACRO replacement

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-library#54]
It generates several errors like this. It looks like it replaces something like $(MSFT_FAMILY_PKG) to 0 since it can't find it

ERROR - Override processing error FILE_NOT_FOUND in file 0/Override/_____SamplePkg/Library/PeiPolicyInitLib/PeiPolicyInitLib.inf.

**Comment by spbrogan** [comment]
#58
