### ISSUE TITLE
Replace variables doesn't work well when there is a space

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-library#56]
!if $ (SECURE_BOOT_ENABLE) == TRUE
becomes 
0!if $ (SECURE_BOOT_ENABLE) == TRUE
Which means we don't resolve it as a conditional

**Comment by matthewfcarlson** [comment]
There's some talk about whether this is spec compliant and if we should even support this

**Comment by Javagedes** [comment]
Closing due to the comments in #68. Feel free to re-open if incorrect.
