### ISSUE TITLE
[Feature]: VSwhere Update? 3.1.7 is latest.

### ISSUE THREAD

**Issue by apop5** [tianocore/edk2-pytool-library#633]
### What does the feature solve?

https://github.com/tianocore/edk2-pytool-library/blob/master/edk2toollib/windows/locate_tools.py#L42

edk2-pytool-library is stuck to version 2.8.4 of vswhere, which was released October 2019.

When would be a good time to consider an update?

### Describe the solution

Since this dependency is embedded in the code, dependabot, etc, don't have the ability to run and alert us to new changes.

Ideally we would be able to promote this dependency to a place where dependabot could handle the dependency.

Or an update Caidance could be considered, and update at specific points.

**Comment by Javagedes** [comment]
completed via #636
