### ISSUE TITLE
DEC Parser does not support structured PCD declarations with braces {}

### ISSUE THREAD

**Issue by mdkinney** [tianocore/edk2-pytool-library#70]
The DEC parser looks for exactly 4 elements in a PCD declaration statement.

There is an optional 5th element that is an open brace '{' to provide a set of 
additional lines for a structured PCD.  Relax the DEC parser to support up to
5 elements and ignore the DEC file lines between the '{' and '}'

**Comment by matthewfcarlson** [comment]
fixed by #71?
