### ISSUE TITLE
Base Parser does not support quoted arguments or IN operators correctly

### ISSUE THREAD

**Issue by mdkinney** [tianocore/edk2-pytool-library#72]
The Base Parser does not support a DSC file conditional statement such as the following:

    !if $(CRYPTO_SERVICES) IN "ALL NONE MIN_PEI MIN_DXE_MIN_SMM"

One of the arguments is a quoted string that needs to be parsed as a single argument.

The IN operator tests for membership.  The Base Parser only looks for 'in' and 
does not support 'IN', 'In', or 'iN'.  Also, when the 'in' operator is present, the
argument to check against membership is converted to an integer.  It should
be converted to a list or set to check for membership.

**Comment by spbrogan** [comment]
closing as this is complete.  Unit test work that is needed will be handled with issue #74
