### ISSUE TITLE
Add ordering to set on Dsc data object

### ISSUE THREAD

**Issue by matthewfcarlson** [tianocore/edk2-pytool-library#82]
I think the order of items matters because there is the case that the later item override the former one.  And the order effects the contents some generated files, for example autogen, makefile and build report. we need to keep those files content order same in each build.  I think a list for val type will be better,  dsc_list?

_Originally posted by @BobCF in https://github.com/tianocore/edk2-pytool-library/diffs/2_

**Comment by corthon** [comment]
Before we lose the info when the PR closes, we should probably include a file/line permalink here somewhere. If it's already here, disregard.
