### ISSUE TITLE
Python code is not compliant with Specs

### ISSUE THREAD

**Issue by gahan9** [tianocore/edk2-pytool-library#97]
Python code is not compliant with the specs defined at [EDK II Python Development Process Specification
](https://edk2-docs.gitbooks.io/edk-ii-python-development-process-specification/content/)

**Comment by matthewfcarlson** [comment]
We already run flake8, I think the only thing missing is mypy, correct?

**Comment by matthewfcarlson** [comment]
We also need to generate documentation

**Comment by gahan9** [comment]
https://edk2-docs.gitbooks.io/edk-ii-python-development-process-specification/content/python_coding_guidelines_and_tools.html specifies guidelines to follow -> PEP 8,  PEP 257, PEP 484, however it seems to follow only PEP 484

**Comment by corthon** [comment]
Thanks! Yeah, we know that there are some places that we'd like to add and improve the formatting, but this is currently a gradual effort (mostly as new PRs come in).

The official policy for Python coding style in the edk2-pytools repos can be found here:
https://github.com/tianocore/edk2-pytool-library/blob/master/docs/developing.md#comments

In general, we actively enforce coding style that can be checked programmatically. We'd love PRs that help expand this programmatic testing and would happily start moving the code to adhere to the test. We're also open to PRs that address underlying convention fixes.
